### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by mudrd8mz** [yedidiaklein/local_video_directory#2]
The `get_videos.php` is a script that allows any (including unauthenticated) users to inject malicious SQL via the keyword parameter, let it execute and read the values.

**Comment by mudrd8mz** [comment]
Other place is player.php via tags argument.

**Comment by yedidiaklein** [comment]
Thanks a lot for your code review, I completely deleted the get_video.php - it was for a connection w/ a repository. and it'll be rewritten securely.

**Comment by yedidiaklein** [comment]
fixed, using moodle question marks way
