### ISSUE TITLE
Does not work on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [yedidiaklein/local_video_directory#4]
![image](https://cloud.githubusercontent.com/assets/85831/24100144/02affce2-0d73-11e7-9c0f-d54926aea2e1.png)

**Comment by mudrd8mz** [comment]
I know that your plugin's description reads "This plugin was developped and tested on linux w/ mysql/mariadb DB - there's a good chance that it'll not work well on other environment." But for the approval in the plugins directory, we try to achieve cross-db compatibility.

Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Cross-DB_compatibility

**Comment by mudrd8mz** [comment]
In this particular case, it might just the issue with double quotes.

**Comment by yedidiaklein** [comment]
checked and fixed on postgres... (also major code rewrite was done...)
