### ISSUE TITLE
Windows ffmpeg location error

### ISSUE THREAD

**Issue by martinvivek** [yedidiaklein/local_video_directory#5]
when i enter the path it says invalid, is that  i made anything wrong? if i enter  "/ffmpeg/bin/ffmpeg" it  accepting
![image](https://cloud.githubusercontent.com/assets/7712010/24329572/1e6ef5b4-1228-11e7-8f4b-16a72e428e16.png)

**Comment by nzn-openapp** [comment]
Thanks Martin. I think this is happening because we depended on moodle's PARAM_PATH validation constant to validate the value entered here. It's also what takes care of the slash conversion, incidentally. We'll have to use a different method maybe. Investigating...

**Comment by nzn-openapp** [comment]
Hi Martin. Our latest version now addresses your issue and give the possibility of optionally designating drive letters if the system detects that the OS that Moodle is running on is a version of Windows. Thanks again for trying out our plugin!
